apiVersion: v1
kind: Service
metadata:
  name: tearoma-frontend-service
spec:
  selector:
    app: tearoma-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This will expose it to the internet
